const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
    minlength: 3,    // FIXED: Changed from min
    maxlength: 20,   // FIXED: Changed from max
    unique: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
    maxlength: 50,   // FIXED: Changed from max
  },
  password: {
    type: String,
    required: true,
    minlength: 8,    // FIXED: Changed from min
  },
  gender: {
    type: String,
    enum: ["male", "female"],
    default: "male",
  },
  isAvatarImageSet: {
    type: Boolean,
    default: false,
  },
  avatarImage: {
    type: String,
    default: "",
  },
  lastSeen: {
    type: Date,
    default: Date.now,
  },
  blockedUsers: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
  ],
  statusMessage: {
    type: String,
    default: "Available",
    maxlength: 50,   // FIXED: Changed from max
  },
  statusIcon: {
    type: String,
    default: "💬", 
  },
  bio: {
    type: String,
    default: "Hey there! I am using Snappy.",
    maxlength: 150,  // FIXED: Changed from max
  },
  interests: {
    type: [String],
    default: [],
  },
  
  // --- NEW FEATURES ---
  
  // Push Notification Token (Firebase Cloud Messaging)
  fcmToken: { 
    type: String, 
    default: "" 
  },
  
  // E2EE Public Key (Generated by frontend WebCrypto API)
  publicKey: { 
    type: String, 
    default: "" 
  } 
});

module.exports = mongoose.model("User", userSchema);